# -*- coding: utf-8 -*-
{
    'name': "Theme Alan",
    'category': 'Theme/eCommerce',
    'version': '2.6',
    'license': 'OPL-1',
    'author': 'Atharva System',
    'support': 'support@atharvasystem.com',
    'website' : 'https://www.atharvasystem.com',
    'live_test_url': 'https://alan-v18.atharvasystem.com',
    'description': """ A powerful, multipurpose eCommerce theme designed to elevate any business whether you're in Electronics, Fashion, Sports, Beauty, Furniture, or beyond""",
    'summary': """ A powerful, multipurpose eCommerce theme designed to elevate any business whether you're in Electronics, Fashion, Sports, Beauty, Furniture, or beyond""",
    'depends': ['atharva_theme_base'],
    'data': [
        'views/shop/template.xml',
        'views/shop/shop.xml',
        'views/shop/layout.xml',
        'views/product/template.xml',
        'views/product/product.xml',
        'views/mixins.xml',
        'data/product_queries_mail.xml',
        'views/snippets/s_img_hotspot.xml',
        'views/b2b_views.xml',
        'views/headers_footers/header.xml',
        'views/headers_footers/footer.xml',
        'views/headers_footers/options.xml',
        'views/snippets/s_snippet_builder.xml',
        'views/snippets/snippets.xml',
        'views/snippets/s_products.xml',
        'views/snippets/s_category_product.xml',
        'views/snippets/s_brand_product.xml',
        'views/snippets/s_category.xml',
        'views/snippets/s_brand.xml',
        'views/snippets/s_website_builder.xml',
        'views/snippets/s_product_banner.xml',
        'views/snippets/s_blog_slider.xml',
        'views/snippets/s_megamenu.xml',
        'views/snippets/s_mobile_preview.xml',
        'views/ai_recommanded_product/template.xml',
    ],
    'assets': {
        'web._assets_primary_variables': [
            '/theme_alan/static/src/scss/variables/primary_variables.scss.scss',
        ],
        'web._assets_frontend_helpers': [
            '/theme_alan/static/src/scss/variables/bootstrap_overridden.scss',
        ],
        'web.assets_frontend': [
            '/theme_alan/static/src/js/frontend/**/*.js',
            '/theme_alan/static/src/scss/base/**/*.scss',
            '/theme_alan/static/src/scss/feather/iconfont.scss',
            '/theme_alan/static/src/scss/product/**/*.scss',
            '/theme_alan/static/src/scss/shop/**/*.scss',
            '/theme_alan/static/src/scss/header/**/*.scss',
            '/theme_alan/static/src/scss/footer/**/*.scss',
            '/theme_alan/static/src/scss/dynamic/**/*.scss',
            '/theme_alan/static/src/scss/advance-megamenu/**/*.scss',
            '/theme_alan/static/src/js/snippets/Hotspot/hotspot.xml',
            '/theme_alan/static/src/js/snippets/Hotspot/hotspot.js',
            '/theme_alan/static/src/js/snippets/Hotspot/000.js',
            '/theme_alan/static/src/js/components/**/*',
            '/theme_alan/static/src/js/services/OfferTimer/offer_timer.js',
            '/theme_alan/static/src/documentation/*',
            '/theme_alan/static/src/xml/search_bar.xml',
            '/theme_alan/static/src/js/ai_recommanded_product/000.js',
            '/theme_alan/static/src/js/menu.js',

        ],
        'website.assets_wysiwyg':[
            '/website_sale/static/src/js/website_sale_utils.js',
            '/theme_alan/static/src/js/components/ProductAdvanceInfo/*',
            '/theme_alan/static/src/js/components/LoginPopup/*',
            '/theme_alan/static/src/js/components/QuickView/*',
            '/theme_alan/static/src/js/components/UserInfo/*',
            '/theme_alan/static/src/js/registries.js',
            '/theme_alan/static/src/xml/website_builder/**/*.xml',
            '/theme_alan/static/src/xml/static_snippets/**/*',
            '/theme_alan/static/src/js/snippets/**/*',
            '/theme_alan/static/src/xml/search_bar.xml',
            '/theme_alan/static/src/js/menu_option.js'

        ],
        'website.assets_editor':[
            '/theme_alan/static/src/js/AlanTouch/*',
            '/theme_alan/static/src/js/editor/Menus/*',
        ],
        'web.assets_backend': [
            '/theme_alan/static/src/scss/advance-megamenu/**/*.scss',
            '/theme_alan/static/src/scss/feather/iconfont.scss',
            '/theme_alan/static/src/js/AlanTouch/AlanTouch.scss',
            '/theme_alan/static/src/scss/dynamic/**/*.scss',
            '/theme_alan/static/src/scss/base/hotspot.scss',
        ]
    },
    'price': 222.00,
    'currency': 'EUR',
    'images': ['static/description/alan_description.jpg','static/description/alan_screenshot.gif'],
    'application': False,
}
